### ISSUE TITLE
The dmenu-args flag causes type error

### ISSUE THREAD

**Issue by SteenSchutt** [andykais/bitwarden-dmenu#11]
**Describe the bug**
The `--dmenu-args` flag produces a type error.

**To Reproduce**
I essentially copied your command from the README, tweaking a few of the values.
```
$ bitwarden-dmenu --debug --dmenu-args '-i' --clear-clipboard 30 --session-timeout 3600 --sync-vault-after 3600
/home/steen/.config/nvm/versions/node/v13.13.0/lib/node_modules/bitwarden-dmenu/bin/cli.js:76
const dmenuArgsParsed = dmenuArgs ? dmenuArgs.split(/\s+/) : []
                                              ^

TypeError: dmenuArgs.split is not a function
    at Object.<anonymous> (/home/steen/.config/nvm/versions/node/v13.13.0/lib/node_modules/bitwarden-dmenu/bin/cli.js:76:47)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

I am on version 1.5.5, using Node 13.13.0 (through nvm).

**Expected behavior**
I expected the script to run correctly, as it does upon removing the `--dmenu-args` option.

**Comment by andykais** [comment]
hey there. This is a limitation of the arg parser I use (minimist). It assumes that `--dmenu-args` and `-i` are two different flags.

You can solve this by writing `--dmenu-args='-i'` instead of `--dmenu-args '-i'`. I will update the readme to show this

**Comment by SteenSchutt** [comment]
Great, that did it. Thanks :+1:
