### ISSUE TITLE
Example command in the readme not correct

### ISSUE THREAD

**Issue by paga2004** [andykais/bitwarden-dmenu#12]
**Describe the bug**
When I run the example command provided in the README, I get the following error. I also tried with the flag `--debug`. The output stays the same.

```bash
$ bitwarden-dmenu --dmenu-args '-i' --clear-clipboard 30 --session-timeout 100 --sync-vault-after 3600 --on-error 'xargs notify-send --urgency=low'
/usr/lib/node_modules/bitwarden-dmenu/bin/cli.js:77
const dmenuArgsParsed = dmenuArgs ? dmenuArgs.split(/\s+/) : []
                                              ^

TypeError: dmenuArgs.split is not a function
    at Object.<anonymous> (/usr/lib/node_modules/bitwarden-dmenu/bin/cli.js:77:47)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**To Reproduce**
Run the following command.

```bash
$ bitwarden-dmenu --dmenu-args '-i' --clear-clipboard 30 --session-timeout 100 --sync-vault-after 3600 --on-error 'xargs notify-send --urgency=low'
```
**Expected behavior**
It should open dmenu and just work with the specified arguments like it is descriebed in the usage section.

**Comment by andykais** [comment]
published in [v1.5.6](https://www.npmjs.com/package/bitwarden-dmenu). I appreciate the contribution!
